### ISSUE TITLE
Microsoft IIS And PHP 5.5: upload font-installer.zip copy to Folder "image/data/fonts" don't work

### ISSUE THREAD

**Issue by initialflame** [opentshirts/OpenTshirts#16]
I run opentshirts on a Windows 2012 IIS. The PHP-Version is 5.5.

When i upload/install the fonts over the menu "Opentshirts -> " Install Packs".
After upload it ends with succssful Message. But the Fonts are not on the expected location "image/data/fonts".

My workaround:
Copy the ttf and swf-Files manually to this location.

I think the Problem is somewhere here in the "admin\model\install\font.php"-File.
/*********************_"admin\model\install\font.php" Line 27 ***_*********************_/
@copy('zip://'.$file.'#'.basename(DIR_IMAGE).'/data/fonts/'.$font_obj->font->swf_file,  $font_dir.'/'.$font_obj->font->swf_file);
        @copy('zip://'.$file.'#'.basename(DIR_IMAGE).'/data/fonts/'.$font_obj->font->ttf_file,  $font_dir.'/'.$font_obj->font->ttf_file);
 /**_*********************************************/

My permission looks good in the Folders taht needs write permissions.
There is no Error Message in the Logs. ( It is the same result if i remove the "@" before the copy-command)

**Comment by adamjm7** [comment]
@initialflame Did you ever get this figured out?  If I had to guess, I'd say it's likely your server setup, but I'm not 100% certain on that.  I believe the pack installer relies on a few php libraries that you may not have installed/enabled.  Have you checked your error logs on your server (separate from the error logs in OC)?
