### ISSUE TITLE
 Warning: Please check the form carefully for errors!

### ISSUE THREAD

**Issue by BlackBitZ** [opentshirts/opentshirts#17]
Hello,
i tried to install OpenShirt in OpenCart 2.0 and it was installed but i have few issue,

when i try to edit the product and try to change the status from Disable to Enable and save it, it give the error,  Warning: Please check the form carefully for errors! 

and on the top i got this error:
Notice: Undefined variable: views in C:\xampp\htdocs\Big\admin\controller\product\view.php on line 59

Need Help! 
Note: URGENT!
![opencart](https://cloud.githubusercontent.com/assets/3767901/10583081/6f1f45b6-76a4-11e5-9ea4-46ebcfd520da.png)

Complete ScreenShot is attached with this!

Regards,

**Comment by adamjm7** [comment]
On the Print Views tab, you need to add at least one view.  That's the problem.

That error at the top of the screen will go away once you add a view.

**Comment by BlackBitZ** [comment]
i added a view too... and filled everything, but the same results....!
Shall i provide you a complete video, might that help..?

**Comment by adamjm7** [comment]
It might be easier if I can access the backend.  Can you send me the url and admin info?

**Comment by BlackBitZ** [comment]
sure, i will set it up again and send it.. can i have your email id?

**Comment by printingsource** [comment]
hi adam, please note these emails are on blast... i am on this thread but it is someone else's website....

**Comment by BlackBitZ** [comment]
i have no issue if someone resolves my issue admin! as long as its an open source and someone helps.. i hope you understand!

**Comment by adamjm7** [comment]
@printingsource This is a github thread.  You must be subscribed to notifications.  If you click on the "View on Github" link at the bottom of this email, you can unsubscribe on the right side of the screen.

**Comment by adamjm7** [comment]
@BlackBitZ You filed this issue under the repo for the original OT.  What you're using is the version I modded for OC 2.  I'm going to close this issue on this repo.  Resubmit your issue on https://github.com/m7ws/opentshirts-for-oc2

**Comment by BlackBitZ** [comment]
Sure!
