### ISSUE TITLE
problem with opentshirts v 1.2.4

### ISSUE THREAD

**Issue by christeibel** [opentshirts/OpenTshirts#19]
Hello, I am having trouble with the Install Packs section of opentshirts. I can navigate to this page but there seems to be some elements missing like the upload or submit button (usually on the upper right)

this is what I see...
![screen](https://cloud.githubusercontent.com/assets/17066688/12825131/c11b4098-cb42-11e5-9eb7-52a8553ee571.jpg)

**Comment by adamjm7** [comment]
That upload button requires Flash to work, which Chrome usually has built in by default.  Have you tried a different browser?

**Comment by saumendraindia** [comment]
Hi Admin I am unable to find the Product Pack as well as Font Pack to Download from Opentshirts.com webste. The Download Section doesnot have it. Could you Please sugest me where I can get it .

Thanks and Awaiting Reply.
