### ISSUE TITLE
Is the product abandoned or unsupported ?

### ISSUE THREAD

**Issue by vtrbtf** [opentshirts/OpenTshirts#22]

**Comment by IP-CAM** [comment]
Probably yes, the latest Version is from 2015, and it's made for v.1.5.x.x OC Series.
Ernie - IP_CAM

**Comment by opentshirts** [comment]
The product is under active development in two edition:
1. OpenTshirts free hosted flash edition (works on opencart 3.X)
2.OpenTshirts commercial hosted html 5 edition (works on opencart 3.X, Magento, WordPress (Woocommerce)
This product is and was the world largest online design studio, both new version will release soon less than a month.
Thank you all 
OpenTshirts Team.
